### ISSUE TITLE
Write "Titan for X" series

### ISSUE THREAD

**Issue by swizzlr** [bermudadigitalstudio/Titan#20]
- Titan for Functional Programmers: Titan composes multiple "middleware" functions into a single reducer which maps a request to a response, which can be used as the backend to an HTTP server.
- Titan for node developers: Express.js, but synchronous.
- Titan for Ruby developers: since Swift has no Rack, TitanCore is very similar to a naïve Rack app; TitanRouting is Sinatra

etc.

@skreutzberger thoughts?

**Comment by skreutzberger** [comment]
Good idea to center the examples around existing programming languages for developers coming from other languages. Additionally we can also have one that just shows the very basic things and that should maybe be the first example.

**Comment by swizzlr** [comment]
agreed, keep this in backlog for now before we do the rest of it
