### ISSUE TITLE
Highly extra credit: Implement S4 compatible adapter

### ISSUE THREAD

**Issue by swizzlr** [bermudadigitalstudio/Titan#41]
https://github.com/open-swift/S4

I'd love to see more server compatibility – but I don't know any S4 servers!

**Comment by pvzig** [comment]
This was an early attempt at cooperation between Vapor, Zewo, and Perfect that is functionally dead now. The only two remaining projects still using S4 AFAIK are [Slimane](https://github.com/slimane-swift) and [swifton](https://github.com/necolt/Swifton).
